### ISSUE TITLE
Closing a project with pending changes needs a new dialog

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1317]
1. Have a project open
2. Make pending changes, e.g. move a project item on the Design view
3. Select File->Close project
4. Get greeted by the dialog box we use when quitting Toolbox:

![exit project](https://user-images.githubusercontent.com/19147159/112109710-9252a600-8bba-11eb-87f2-35102506877a.png)

**Expected behavior**

Show a different dialog with wording in title, message and buttons referring to closing the project instead of exiting Toolbox.

**Comment by PekkaSavolainen** [comment]
This was actually done on purpose to save a few lines. Maybe it was not a good idea after all because user's may get confused.

**Comment by manuelma** [comment]
I still think it's a good idea, but we need better words. The setting is also called "Save project at exit" and we may wanna call it "Save project at closing".

If I remember correctly, we repurposed save project at exit for closing project which i think it's good, it just looks like we forgot some final details.

**Comment by soininen** [comment]
Manuel is right, I think. It is the dialog's wording that doesn't work here. If we can find more suitable one which works at Toolbox exit as well it would be just as fine.

**Comment by PekkaSavolainen** [comment]
The setting on `General` page that used to be `Save project at exit` is now `Save project before closing` and the tooltip has been updated to tell the user what this setting does. I meant that using this same setting for saving what the user wants to do in these cases (closing the app, closing the project, creating a project, opening another project) should be fine but the dialog wordings need some work indeed. 

We use exactly the same dialog in multiple places now and we just need to refactor the dialog so that we can pass the title and the message separately for each particular case.

**Comment by soininen** [comment]
Can we update that setting to use Radio buttons on the same go? That is the usual way of letting user choose multiple options. The three-state-checkbox solution very confusing and the Tooltip is not really a good way to explain the intricaties to the user.

**Comment by PekkaSavolainen** [comment]
@rsvtt This may be a good one to start with.
