### ISSUE TITLE
URL names in tool properties

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1388]
@Matomaki pointed out that it is confusing that the URL names in tool properties are very different from what you get when copy them from the source (e.g. data store properties copy button).

E.g. `sqlite:///C:\data\Toolbox_projects\SpineOpt_mini\Input DB.sqlite` vs. `db_url@Input DB`. Could we have the actual address in parentheses or at least as a tooltip? Or are there more elegant solutions?

Also, copying the URL (ctrl-c) in Tool properties gives that `db_url@Input DB`. But should it give the actual address instead?

**Comment by soininen** [comment]
There is also the issue the command line argument passed to a Tool will be a completely different URL as we are creating a database server during execution to make parallel execution work reliably.

Anyway, `db_url@<provider name>` is a resource label and we are moving towards using more labels instead of direct URLs/file paths to allow changing resource's the database/file without breaking other items' settings. I agree we could show the underlying URL as a tooltip and I think we do that already for file resources. Copying the resource label could also copy the actual URL/file path.

**Comment by PekkaSavolainen** [comment]
> Also, copying the URL (ctrl-c) in Tool properties gives that db_url@Input DB. But should it give the actual address instead?

How about a Context-menu for resource labels:
- Copy label to clipboard
- Copy URL to clipboard

**Comment by manuelma** [comment]
What is the user trying to achieve here? Why do they need to copy those URLs? It doesn't feel like we need to 'reveal' this part of our internal mechanics.

**Comment by manuelma** [comment]
To me it looks like the user is trying to do a little hack, run SpineOpt from outside toolbox or something like that? That's great, but not something we should worry to 'facilitate' in my opinion.

**Comment by soininen** [comment]
> It doesn't feel like we need to 'reveal' this part of our internal mechanics.

That is also a valid point. The URL is tied to the label in Data Store and you can copy it from there. Same for file paths that can be found in Data Connection.

**Comment by jkiviluo** [comment]
That moving to labels is a good point. However, this was not about hacking around Toolbox - it's about a user trying to understand what is going on. I think that's really important - not just that it does something like magic, but also that the user starts to build an innate understanding how the process if facilitated.

**Comment by jkiviluo** [comment]
It looks like this is done (tooltip shows the URL)
