### ISSUE TITLE
Restoring a project connection by connection makes items lose some of their settings

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1390]
Currently, we restore project's connections by connecting the items one by one as if the connections were made by user. This does not work so well if there are more than one incoming connection on an item. Consider the following:

An item C has two incoming connections from items A and B that provide file resources that are used by C. When the project is restored from disk, A, B and C are constructed followed by their connections. When the first connection is restored (say, A -> C) C gets its resources updated. However, since only A is at this point connected to C, C doesn't get the resources from B and may drop all settings regarding B's resources. When the connection B -> C is reestablished C has seemingly forgotten its settings regarding B.

We end up in a situation where items that have more than one incoming connection seem to forget some of their settings when loading a project.

We are employing some workarounds, see #1380 and the discussion in #1382 but we should really fix the root of the problem.

**Comment by manuelma** [comment]
Nice. I actually wanted to do this in #1382 but seemed just a little bit too much of a change right now.

I guess the main thing I was missing was something like `ProjectItem.all_resources_updated(upstream_resources, downstream_resources)` that I could call at project loading after everything was in place.

We have `upstream_resources_updated()` and `downstream_resources_updated()` that work great 'in interactive mode', but not at project loading since each of them might want to modify the item's state irreversible.

It's an interesting problem, because at the moment we need to avoid those irreversible modifications in both of those methods. Which at the same time 'feels right'. Disconnecting a link shouldn't change the item state, right? The item should be able to recover it's state after the connection is restablished.

So if we fulfill that last requirement, we also don't have a problem in loading the project incrementally as we do...

**Comment by manuelma** [comment]
Sorry for spamming. Thinking more into it, undo/redo is a very strong reason to make those unilateral state modifications illegal. We need to be able to remove a link, undo the operation, and recover the previous state.

**Comment by soininen** [comment]
Items could also save their incoming resources to `project.json`. Then we could just omit the updates when loading the project or pasting items on the Design view.

It is an interesting problem, indeed!

**Comment by soininen** [comment]
> Disconnecting a link shouldn't change the item state, right? The item should be able to recover its state after the connection is restablished.

Are you trying to say that those workarounds might be what we actually want? It would be a bit of 'hidden' responsibility for the items but how e.g. Exporter now remembers its previous databases is actually a pretty nifty feature.

**Comment by manuelma** [comment]
> Are you trying to say that those workarounds might be what we actually want?

**Comment by soininen** [comment]
> What do you think?

I'm starting to feel the same way. We'd need to revise `up/downstream_resources_updated()` methods of each project item and try to come up with best ways on how to deal with disappearing resources. It would probably improve the overall usage experience too as it did with Exporter and Tool.

**Comment by soininen** [comment]
We've implementing the idea of avoiding irreversible side effects when updating items' resources for a while now and it seems to work nicely.
