### ISSUE TITLE
Consider renaming `Copy` in the entity tree context menu

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/Spine-Toolbox#1640]
Currently, right-clicking on a database object/relationships opens the following drop-down menu, with the option to `Copy` the object/relationship:
![image](https://user-images.githubusercontent.com/77660814/150784942-4c74c9b6-fa79-48d8-94ef-c21e17a4036f.png)
However, there's not a `Paste` option available anywhere, nor does `Ctrl+V` do anything meaningful. Copying and pasting a database object/relationship into e.g. notepad results in only the name of the object/relationship being pasted.

The current `Copy` function seems unfinished, and is pretty misleading.

**Comment by jkiviluo** [comment]
It copies the entity names as text and they can be pasted into other programs (or e.g. to Parameter value window). There is also 'duplicate' object, which prompts to give another name. There has to be another name, since DB does not allow duplicate names.

Maybe we should just change the 'copy' to 'copy name(s) as text'. And maybe duplicate could be right under copy. Also duplicate could just duplicate with name 'old name 1' without opening a prompt. Then 'old name 1' would be active, fully selected and thus ready to be modified or renamed by the user. Duplicate could also duplicate multiple entities at once.
