### ISSUE TITLE
Is there a template for results datastore?

### ISSUE THREAD

**Issue by rputris** [spine-tools/Spine-Toolbox#1651]
Hello @manuelma ,

I have executed my model successfully but I have nothing in the results database. When I look at example models I see different objects and relationships in the results database, I have searched the documentation but I have not found how to correctly create the necessary object tree and relationship tree structure to view the results from my model. How can I set up me results database correctly? Is there a template for this? I know there is one for the input database but it does not have the same sort of structure I see in the examples. 

I have even used the template model and have not gotten this part to work yet. If you can send me some steps of what I can do to correctly set it up that would be greatly appreciated. Thank you.

**Comment by DillonJ** [comment]
Hi @rputris 

It's true that there isn't a lot of documentation about outputs, but there is something here: https://spine-project.github.io/SpineOpt.jl/latest/concept_reference/Object%20Classes/#output

In short, you need to create an output in your input datastore that corresponds to every output that you want in your output datastore. If you have imported the SpineOpt template, all available outputs should exist by default. You just need to create a `report__output` relationship to include the relevant output in your report. Additionally, you need to create a `model__report` relationship to associate your report with your `model`.

To import the SpineOpt template, in DB Editor, select file->import, change the file type to JSON file and then navigate to SpineOpt/templates/spineopt_template.json. 

It may well be that there are some outputs in your output db, but it isn't exactly obvious where they are. This can because SpineOpt adds additional dimensions to the outputs such as the report object and the stochastic structure, so they may look unfamilliar. Typically, the results will be in timeseries format and you will either need to doubleclick on a timeseries value to visualise it, or use the pivot view.

If you want to post your output db, I can check this for you (zip it up or rename it as a zip file to get past githubs file type filter).

**Comment by DillonJ** [comment]
Hi again @rputris. I have added a documentation section on output data here: https://spine-project.github.io/SpineOpt.jl/latest/getting_started/output_data/

It's still a work in progress but hopefully is useful.
