### ISSUE TITLE
Python tool spec editor takes 2 to 3 seconds to load

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1809]
This is of course not dramatic, but I thought we could load the jupyter kernel information only if the spec is set to use the Jupyter console - so specs using the homemade console would load instantly.

**Comment by manuelma** [comment]
I just also noticed that loading the jupyer kernel info also blocks the UI. We can fix that in this same issue I think.

**Comment by manuelma** [comment]
I am happier with this now. We might also wanna consider implementing the same kind of helper widget but for julia specs - in another issue.

**Comment by jkiviluo** [comment]
Great! It is very good to get rid of these slow things in the UI - when one uses a lot, they are really distracting.

**Comment by PekkaSavolainen** [comment]
I think I broke this a bit. It now loads the kernel specs also for Python Tools that have Basic Console selected. Will fix.

**Comment by manuelma** [comment]
Nice one @PekkaSavolainen - that's good, but how about the original purpose which is not to load the kernel specs at all if the tool is not python or if it's python but set to use the Basic console?

**Comment by PekkaSavolainen** [comment]
> Nice one @PekkaSavolainen - that's good, but how about the original purpose which is not to load the kernel specs at all if the tool is not python or if it's python but set to use the Basic console?

The kernel specs are not loaded if Tool spec type is not Python. so this is already handled.

If it's Python but set to use Basic Console, the kernel specs are loaded but they are done in a background thread. This I did not dare to change because it might break something else and I'm not sure if it's worth the effort at this time. Things that may break include Basic and Jupyter Console radio button undo-redo, loading saved kernel specs, taking users default Python Tool Spec selections into account when creating new Tool specs, switching between different tool types, etc.

**Comment by manuelma** [comment]
Thank you @PekkaSavolainen 

I think it would be good if we could skip loading the kernel specs even if it is in another thread. A lot of users will *never* care for the kernel specs as they will be using the homemade console 100% of the time. I even wonder if we should try and drop the jupyter console altogether at some point?

**Comment by PekkaSavolainen** [comment]
> A lot of users will never care for the kernel specs as they will be using the homemade console 100% of the time. I even wonder if we should try and drop the jupyter console altogether at some point?

I would not say it's 100% for the homemade console :) but I do have wondered if we really want to keep both consoles.
