### ISSUE TITLE
Automate deployment process

### ISSUE THREAD

**Issue by OleMussmann** [spine-tools/Spine-Toolbox#1934]
Deployment is manual and somewhat brittle. A deployment script could reduce human error.

**Comment by soininen** [comment]
The deployment script should be written in Python, be placed in `<repository root>/bin/` in Spine-Toolbox, spine-items, spine-engine and Spine-Database-API. There could be a `.bat` file calling the Python script for Windows users but that is not strictly necessary as the script will be used by developers only.

**Comment by suvayu** [comment]
## Rationale & Design
The current release process has manual steps.  Mostly
- to manage the version information, and
- to ensure the consistency of the dependency requirements with other Spine packages

So I propose the following workflow:
1. use [`setuptools_scm`](https://github.com/pypa/setuptools_scm/) to manage versions dynamically using git tags
2. use a release tagging script to generate the next version number, update the dependency requirements, and create the git tag
3. push the tags to github, and publish the packages to pypi using github actions

For the tagging script to work, the build system of all the projects should be similar.  Since it requires automatic updates, I chose `pyproject.toml` as the library to r/w toml is quite mature, and both `setup.py` and `setup.cfg` are now deprecated.  The current spine packages mostly use `setup.cfg` except Spine Engine.  But even in that case, the `setup.py` is simple, so migration should be straightforward.

## Toy implementation
I implement the above scheme in a set of 3 toy repos, where 2 of them have circular dependency:
- [scm](https://github.com/suvayu/scm) hosts the package `sa-foo`
- [scm-dep](https://github.com/suvayu/scm-dep) hosts the package `sa-bar`
- [scm-base](https://github.com/suvayu/scm-base) hosts the package `sa-baz`
- `sa-foo` and `sa-bar` have a cyclic dependency

Release is done by running the [`tag_release.py`](https://github.com/suvayu/scm/blob/master/tag_release.py) script.  And each repo has its own action to build and publish wheels and tarballs to PyPI.  At the moment they are platform independent wheels, but when the need arises switching to platform dependent wheels should be possible.

For more details, see [notes.md](https://github.com/suvayu/scm/blob/master/notes.md).

**Comment by suvayu** [comment]
You can now test with the branches in the linked PRs.  all the branches are named `ci`. So in your config, you can add the following section to set the branch names:
```toml
[tool.conductor.branches]
spinetoolbox = "ci"
spine_items  = "ci"
spine_engine = "ci"
spinedb_api  = "ci"
```
**Note**: the automatic versioning depends on versioned git tags existing (X.Y or X.Y.Z).  So you will need to create these tags.  These are the commits and the corresponding tags to get everything correct:
| repo               | commit   |    tag |                                                                                                                                                                                                
|--------------------|----------|--------|
| Spine-Toolbox      | 0f1d6984 | 0.6.18 |
| spine-items        | spine-tools/spine-items@090b963  | 0.20.0 |
| spine-engine       | spine-tools/spine-engine@1aaa78e  | 0.22.0 |
| Spine-Database-API | spine-tools/Spine-Database-API@2047c6a  | 0.29.0 |

**Comment by PekkaSavolainen** [comment]
I'm having a bit of problems testing this. I checked out all 4 `suvayu/ci" branches. Then added this to Spine Toolboxes pyproject.toml

```
[tool.conductor]
packagename_regex = "spine(toolbox|(db){0,1}_[a-z]+)"  # package name on PyPI

[tool.conductor.dependency_graph]
spinetoolbox = ["spine_items", "spine_engine", "spinedb_api"]
spine_items  = ["spinetoolbox", "spine_engine", "spinedb_api"]
spine_engine = ["spinedb_api"]
spinedb_api  = []

[tool.conductor.repos]
spinetoolbox = "."
spine_items  = "../SPINEITEMS"
spine_engine = "../SPINEENGINE"
spinedb_api  = "../SPINEDBAPI"

# default
[tool.conductor.branches]
spinetoolbox = "suvayu_toolbox_ci"
spine_items  = "suvayu_items_ci"
spine_engine = "suvayu_engine_ci"
spinedb_api  = "suvayu_dbapi_ci"
```
Then I tried running tag_release.py but this happened.

```
C:\data\GIT\SPINETOOLBOX>python ..\CONDUCTOR\tag_release.py -b patch
C:\Python310\lib\site-packages\setuptools_scm\version.py:84: UserWarning: tag 'in_0.6.0-final.2' no version found
  warnings.warn(f"tag {tag!r} no version found")
Traceback (most recent call last):
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 294, in <module>
    summary = tag_releases(config["repos"], args.bump_version)
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 221, in tag_releases
    _next_versions = guess_next_versions(_repos, bump_version)
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 119, in guess_next_versions
    versions = [
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 120, in <listcomp>
    version.parse(get_version(root=repo.working_dir, version_scheme=version_scheme))
  File "C:\Python310\lib\site-packages\setuptools_scm\__init__.py", line 146, in get_version
    maybe_version = _get_version(config)
  File "C:\Python310\lib\site-packages\setuptools_scm\__init__.py", line 153, in _get_version
    parsed_version = _do_parse(config)
  File "C:\Python310\lib\site-packages\setuptools_scm\__init__.py", line 100, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "C:\Python310\lib\site-packages\setuptools_scm\_entrypoints.py", line 66, in _version_from_entrypoints
    version: ScmVersion | None = _call_entrypoint_fn(root, config, ep.load())
  File "C:\Python310\lib\site-packages\setuptools_scm\_entrypoints.py", line 40, in _call_entrypoint_fn
    return fn(root, config=config)
  File "C:\Python310\lib\site-packages\setuptools_scm\git.py", line 181, in parse
    return _git_parse_inner(
  File "C:\Python310\lib\site-packages\setuptools_scm\git.py", line 224, in _git_parse_inner
    return meta(
  File "C:\Python310\lib\site-packages\setuptools_scm\version.py", line 226, in meta
    parsed_version = _parse_tag(tag, preformatted, config)
  File "C:\Python310\lib\site-packages\setuptools_scm\version.py", line 203, in _parse_tag
    assert version is not None
AssertionError

C:\data\GIT\SPINETOOLBOX>
```


Then I added tags to all four **master** branches (e.g. 0.6.18 to Toolbox). I could not add them to the branches in your fork (Permission denied). Then this happened.

```
C:\data\GIT\SPINETOOLBOX>python ..\CONDUCTOR\tag_release.py -b patch
Repository: C:\data\GIT\SPINETOOLBOX
## suvayu_toolbox_ci...suvayu_fork/ci
M  pyproject.toml (1)
Select the files to add (comma/space separated list): 1
Traceback (most recent call last):
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 294, in <module>
    summary = tag_releases(config["repos"], args.bump_version)
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 243, in tag_releases
    msg = invoke_editor(repo, next_version)
  File "C:\data\GIT\CONDUCTOR\tag_release.py", line 205, in invoke_editor
    ret = subprocess.run([*EDITOR.split(), tmp_file.name])
  File "C:\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\data\GIT\SPINETOOLBOX>
``´

I put in *1* to the `Select files to add` guestion, just like in your (@suvayu)  example in spine_conductor repo. What files is it trying to add here?

**Comment by PekkaSavolainen** [comment]
I noticed that even though running tag_release.py failed in the above listing, it did update the pyproject.toml dependencies sections. For example, SPINEITEMS/pyproject.toml was updated to this

```
dependencies = ["pyside6 >= 6.4.0, !=6.4.2, < 6.5.0", "pyodbc >=4.0", "sqlalchemy >=1.3, <1.4", "pygments >=2.8", "numpy >=1.20.2", "spinedb_api>=0.29.1", "spine_engine>=0.22.1"]
```

I see a problem here. If you try installing any of the older spinetoolbox versions from PyPi right now (e.g. `pip install "spinetoolbox==0.6.15"`, it is broken. This is because the dependencies have not been locked. So, the required `spinetoolbox`, `spine-items`, `spine-engine`, and `spinedb-api` package versions should be **locked** to a specific version. In addition, we don't know if there's going to be breaking changes in third-party packages in upcoming releases, so we should **limit** their version as well. So the above dependencies should IMO look something like this.

```
dependencies = ["pyside6 >= 6.4.0, !=6.4.2, < 6.5.0", "pyodbc <5.0", "sqlalchemy >=1.3, <1.4", "pygments <2.9", "numpy <1.21", "spinedb_api==0.29.1", "spine_engine==0.22.1"]
```

Or is there another way to make sure that what we publish to PyPi will work from from here to eternity?

**Comment by suvayu** [comment]
@PekkaSavolainen The crashes are happening probably because the initial git tags are not present.  You need to tag the appropriate commits with the current version tags (as mentioned in the [comment] (https://github.com/spine-tools/Spine-Toolbox/issues/1934#issuecomment-1591245394). These tags should also be pushed to the repo after merging the PRs.  `setuptools_scm` generates the version number from the git tags.

About locking the dependencies, my thinking was people doing a pip install will get the latest version of all spine packages, so we only need a `>=` for released packages.  If we do an exact equality (`==`), then the dev version would break, and the workflow to avoid that would become more complicated:
- check changes
- commit with locked version (`spine* == <version>` )
- tag release
- commit again unlocking the version (`spine* >= <version>`)
While possible, I don't see what this actually adds (unless of course there's good reason for a user to install an older version of spinetoolbox).

@soininen As for locking versions of dependencies, that is a bad practice because you do not know what other packages the user has installed.  It could easily create a situation where the user has incompatible packages and is forced to use multiple virtual environments in their working environment.

**Comment by suvayu** [comment]
@PekkaSavolainen 
> I put in 1 to the Select files to add guestion, just like in your (@suvayu) example in spine_conductor repo. What files is it trying to add here?

In this case, the script should be adding `pyproject.toml` (since you selected 1), and then invoke the editor for the commit message.  I think here it's the editor command for the commit message that's failing.  Do you have either `$EDITOR` set, or `vim` present in your path?  Because In the script I set editor like this: `EDITOR = os.environ.get("EDITOR", "vim")`.  So if you could check what you get, that would be helpful

**Comment by suvayu** [comment]
Okay, I have a suggestion for the spine package version pinning that's not as aggressive.

Say, when we release `spinetoolbox` 0.6.18, `spinedb_api` is at 0.29.0.  We limit `spinedb_api` version to `spinedb_api >= 0.29.0, < 0.30.0`.  Now we have to maintain the discipline that we don't do large changes in point releases (spinedb_api @ 0.29.x etc, and spinetoolbox @ 0.6.19, etc), and when we make a big change, we bump the minor number (0.7.0 & 0.30.0).  Would that work?

**Comment by suvayu** [comment]
I have been thinking.  If we want to version lock everything (including dependencies), then we should consider switching the build process entirely to something that is more compatible with that style of releases, say [`poetry`](https://python-poetry.org/).  It uses lock files in the same style as nodejs.

**Comment by jkiviluo** [comment]
Sounds like a good idea, but I don't know enough to give any real comments.

**Comment by suvayu** [comment]
Hi @jkiviluo maybe we can discuss some of this next week.  There are multiple ways to go about this depending on the typical user base.  It's difficult for me to recommend something as I feel I don't have a (reasonably) clear view of all the current and future users.

I can prepare a list of possibilities with pros & cons for the next developer meeting, and pick one option.
