### ISSUE TITLE
Scenario/Alternative Pivot Not working

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1940]
In latest toolbox you can no longer use the scenario pivot option to choose what scenarios contain what alternatives.

![image](https://user-images.githubusercontent.com/7080191/214608565-0b91564c-bf7c-4a26-a8cb-c050fa9a0ba1.png)

**Comment by manuelma** [comment]
This must be related to Qt6 changes - will fix now.

**Comment by manuelma** [comment]
It was actually a mix: visualizing the checkboxes was broken due to PySide6 not supporting comparisons between ItemFlag and int anymore - easy fix.
Checking the checkbox (i.e. adding/removing scenario alternatives) was broken due to a miss in the refactoring for the more asynch fetching - also straightforward fix.

We need to write some tests before closing this.

**Comment by DillonJ** [comment]
I'm sure you know, but just in case, you do more than check the boxes - you indicate the write order also (a number appears in the box indicating the write order of the alternative).

**Comment by manuelma** [comment]
> I'm sure you know, but just in case, you do more than check the boxes - you indicate the write order also (a number appears in the box indicating the write order of the alternative).

yes :)

**Comment by soininen** [comment]
@manuelma Is there something still to be done here? Unit tests?

**Comment by manuelma** [comment]
Yes @soininen probably we don't have any tests for this, other than that it seems to be working ok.

**Comment by jkiviluo** [comment]
I'll move this v0.8 - I suppose it's ok to leave the tests there.

**Comment by soininen** [comment]
The issue has been fixed but I feel the ship has sailed for the tests. Lets just close this.
