### ISSUE TITLE
Installation of Spine Toolbox - No Python at 'C:\Users\<UserName>\AppData\Local\Programs\Python\Python39-32\python.exe'

### ISSUE THREAD

**Issue by JaKehrl** [spine-tools/Spine-Toolbox#1958]
Hi community!
I have been struggling to install the Spine Toolbox. Please find below steps. Maybe someone is facing the same issues and could help me out. 
I used the following instruction: 
https://github.com/spine-tools/Spine-Toolbox#installation-with-python-and-pipx

The screenshot for every single step can be seen in attached folder. Is there anything else I need to consider, e.g. creating a virtual environment (which should be automatically done by _pipx_?)?

1.	Ensure that no python is installed
2.	Install Python 3.9
3.	Get the latest version of pip (pip is a package manager for Python) 
4.	Install pipx. pipx helps in creating an isolated environment for Spine Toolbox to avoid package conflicts.
5.	Restart the terminal or re-login for the changes of the latest command to take effect.
6.	Choose which Toolbox version to install

 
[No Python At... (File with Screenshots).pdf](https://github.com/spine-tools/Spine-Toolbox/files/10676512/No.Python.At.File.with.Screenshots.pdf)

**Comment by soininen** [comment]
I uninstalled all Pythons on my system and then tried to replicate the issue here. Unfortunately (or perhaps fortunately for me...) Spine Toolbox was installed successfully. There were two differences I noticed (not sure how important these are): on my system, `pipx` got downloaded while on yours, it was found in the cache meaning that it had been previously installed ("Using cached pipx-1.1.0..." on the screenshot at step 4). Further, Python is installed in <home>\AppData\Local\Programs\Python\Python39\python.exe on my system - note the differences in the last directories Python39 vs. Python39-32. Have you checked your environment variables? Maybe there is yet another Python in PATH?

**Comment by PekkaSavolainen** [comment]
@JaKehrl did you figure out the issue? If not, there are a couple of things you could do to help us troubleshoot the problem. Please open Command prompt (cmd.exe), run the following commands, and copy-paste the output here:

1. `where python`
2. `where pip`
3. `where pipx`
4. `echo %PATH%`

**Comment by JaKehrl** [comment]
@PekkaSavolainen I haven´t figured out the problem. When I use your commands, I get the following result: 
![image](https://user-images.githubusercontent.com/124700754/217580769-f6c8aea9-6f2b-4cd8-8dc3-fa7e3f6d8228.png)

I have tried to reinstall Python. However, as @soininen has already noticed, not all python packages get removed. Do you know a way on how to ensure that Python and all through python installed packages & paths are removed from the Windows Engine? 

Then I could try to reinstall python.

**Comment by PekkaSavolainen** [comment]
Not a lot of help there but please try reinstalling pipx by doing the following:

1. `pip uninstall pipx`
2. Delete folder `C:\Users\jakob\.local\pipx`
3. Reinstall pipx without cache `python -m pip install --no-cache-dir --user pipx`
4. python -m pipx ensurepath
5. Restart cmd.exe
6. Install the app `python -m pipx install spinetoolbox`

**Comment by JaKehrl** [comment]
@PekkaSavolainen Thank you very much! Problem is solved. Now I hope SpineOpt won´t cause any issues. I will attach a pdf with screenshots with all your commands. 
[GitHub-Success.pdf](https://github.com/spine-tools/Spine-Toolbox/files/10688286/GitHub-Success.pdf)

**Comment by PekkaSavolainen** [comment]
I managed to reproduce this. I had previously installed pipx on Python 3.8 (with `--user` flag). Since then I've moved to Python 3.11 and installed pipx there as well (with `--user` flag). I noticed that there's a pyvenv.cfg file in *C:\Users\\\<user name>\\.local\pipx\shared* folder which points to Python 3.8. When I removed Python 3.8 and tried `pipx install spinetoolbox`, this happens

```
C:\>pipx install spinetoolbox --force
Installing to existing venv 'spinetoolbox'
No Python at 'c:\python38\python.exe'
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\ttepsa\.local\pipx\logs\cmd_2023-02-10_12.42.32_pip_errors.log
...
```

There must be some additional command that we should give to pipx when installing it so that the pyvenv.cfg file is updated to point to the latest Python.
