### ISSUE TITLE
Tool spec editor can have the same file as the main program file and as an additional program file

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2128]
It is possible in the tool spec editor to choose a file as the main program file and then also choose the same file as an additional file. When the file is then deleted from the additional file, it is also deleted from the main program file selection. If you have more distinct additional files besides the duplicate of the main program file, you can delete the main program file from the additional files list and the file below that will become the new main program file. If then the new main program file is again added to the additional files and then again deleted, toolbox sometimes crashes.

**Comment by jkiviluo** [comment]
I suppose this needs to deal with the option to include full directories as well. The main program file can be in the same directory with the additional program files. Or maybe that's not causing the observed behaviour?

Can this happen with input or output files too?

**Comment by soininen** [comment]
> Can this happen with input or output files too?

You can specify same files as input and output, e.g. have `data.csv` as an input file and `*.csv` as output - in this case `data.csv` would be copied to the work directory before executing and afterwards, because the file has `.csv` extension, it would be copied to the results directory. I wouldn't consider this as a bug --- users should separate the files by putting them into different directories e.g. `output/*.csv` for output files to avoid mixing them up.

**Comment by PiispaH** [comment]
> I suppose this needs to deal with the option to include full directories as well.

Yes this is also an issue.
