### ISSUE TITLE
Pack CSV files choice freezes Toolbox

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2129]
Trying to choose 'Pack CSV files' in the arrow causes Toolbox to freeze at least in the FlexTool workflow

![image](https://github.com/spine-tools/Spine-Toolbox/assets/40472544/7c2f06e5-1aa7-49cf-af56-488f9f334ccf)

**Comment by soininen** [comment]
The connection between the Export_to_CSV and FlexTool3 items creates the `datapackage.json` files when the "Pack CSV files" option is checked. Since this operation is done in the UI thread, it may freeze the UI if the exporter contains a large number of output files.

The solution is to clean up the exporter's `output` directory manually.

We could generate the datapackage files in a separate thread/process which would prevent the UI thread from freezing but it is not straightforward to implement. I am unsure if the development effort spent to do it would be worth it, especially since users are not expected to repeatedly check and uncheck the option, they rarely have hundreds of `.csv` files, and they may be able to just delete the files before clicking the checkbox.

**Comment by soininen** [comment]
Just realized we execute the packaging procedure also every time a project is opened which can drastically affect load times. I think it makes looking into this issue worth the while.

**Comment by jkiviluo** [comment]
Seems not to be an issue anymore.
