### ISSUE TITLE
Importer makes SpineToolBox crash

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2161]
Hi,
I have created a custom importer in SpineToolBox (using [FlexTool](https://github.com/irena-flextool/flextool))
![image](https://github.com/spine-tools/Spine-Toolbox/assets/62605130/d231fceb-3a88-4f26-b134-d5d413fd8f79)

However, when I go in my Importer and try to select a worksheet of my Excel, SpineToolbox suddenly closes, and in the Anaconda prompt I have the following error:

> Traceback (most recent call last):
  File "C:\Users\MyName\Spine-Toolbox\src\spine-items\spine_items\importer\widgets\import_mappings.py", line 155, in _change_flattened_mappings
    if not current.isValid():
  File "C:\Users\MyName\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 413, in parent
    index_item = index.internalPointer()
  File "C:\Users\MyName\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 413, in parent
    index_item = index.internalPointer()
  File "C:\Users\MyName\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 413, in parent
    index_item = index.internalPointer()
  [Previous line repeated 1 more time]
  File "C:\Users\MyName\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 378, in index
    raise RuntimeError("Cannot create index.")
RuntimeError: Cannot create index.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/62605130/21c64f59-139e-4e4b-9eeb-b7f3e1852af0)

Happy if you can help with this issue.
Many thanks

**Comment by PekkaSavolainen** [comment]
Anaconda environments are not supported (see Readme.md Troubleshooting section). Please use miniconda or venv.

**Comment by PekkaSavolainen** [comment]
Anaconda was not to blame here because this seems to happen with miniconda and venv as well. BUT this happens only on a single system that I know of so far. It seems that nobody else is able to reproduce this. Things tried so far include, upgrading requirements, recloning the repo, trying different Python versions, reinstalling PySide6. trying PySide 6.5.1.1.

Steps to reproduce:
- Make a new project
- Make an Importer
- Make a Data Connection
- Add an Excel file to Data Connection
- Connect Data Connection to Importer
- Double-click importer and select Excel
- Click on a sheet name in Source tables -> Crash

And here's the traceback
```
(toolboxv10) C:\Users\ICourt\Spine-Toolbox>python -m spinetoolbox
TypeError: print_exception(): Exception expected for value, str found
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ICourt\Spine-Toolbox\src\spine-items\spine_items\importer\widgets\import_mappings.py", line 164, in _change_flattened_mappings
    if not current.isValid():
  File "C:\Users\ICourt\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 413, in parent
    index_item = index.internalPointer()
  File "C:\Users\ICourt\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 413, in parent
    index_item = index.internalPointer()
  File "C:\Users\ICourt\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 413, in parent
    index_item = index.internalPointer()
  [Previous line repeated 1 more time]
  File "C:\Users\ICourt\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 378, in index
    raise RuntimeError("Cannot create index.")
RuntimeError: Cannot create index.
```

Any ideas what could be the cause here?

**Comment by PekkaSavolainen** [comment]
Issue https://github.com/spine-tools/Spine-Toolbox/issues/2121 must be related. Almost identical traceback.

**Comment by PekkaSavolainen** [comment]
@sjvrijn Did you find a solution or a reason for #2121 and #2119? This seems to be the same issue here.

**Comment by sjvrijn** [comment]
Haven't found a solution, and I'm indeed running Windows 11. I'll see if I can reproduce this on my Windows 10 machine.

**Comment by soininen** [comment]
Updating PySide6 to 6.5 seems to prevent Toolbox from crashing although there is still a Traceback. However, Importer seems to work otherwise fine so this could be an acceptable workaround for the time being. We should update our requirements accordingly as we currently limit PySide6 to 6.4.

**Comment by daspartha** [comment]
Hi, I am new to spine and trying to follow a youtube tutorial by Juha https://www.youtube.com/watch?v=oRwXwV9tuSo.
I am having exactly same issue as indicated by PekkaSavolainen. 
I have tried with both excel and csv data. Spinetoolbox crashes when I click on one of the source tables (sheets).
I am using Anaconda with Python 3.9.16 on windows 10. 

![spine](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/285917f8-c84f-43b0-a1ed-465c604033b3)

**Comment by e-zaline** [comment]
>

**Comment by e-zaline** [comment]
Hi @daspartha,
If you have the same traceback, have you tried what was suggested by @soininen, updating PySide 6 to 6.5?
For me it solved the issue.


> Updating PySide6 to 6.5 seems to prevent Toolbox from crashing although there is still a Traceback. However, Importer seems to work otherwise fine so this could be an acceptable workaround for the time being. We should update our requirements accordingly as we currently limit PySide6 to 6.4.

**Comment by daspartha** [comment]
Hi @e-zaline 
I have now uninstalled anaconda and using only Python 3.9.0.
I have PySide6 version 6.4.3.
But I am still facing the same issue.
Spinetoolbox crashes when I click on any source table.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/3b7c77a4-d380-45ea-9eb7-7f7e75886b22)

**Comment by daspartha** [comment]
Hi @e-zaline 

I am now using python 3.9.0 instead of the anaconda distribution.
When I update Pyside6 to 6.5 python tells me that spinetoolbox is not compatible with this version of PySide6.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/c142f083-ff63-4a99-a55c-1ac67685efc7)

I am still facing the same issue as I indicated before. Spinetoolbox crashes when I click on the source table.

**Comment by jkiviluo** [comment]
For anyone else reading this - the issue went away after updating and then doing a program or computer restart (unsure which one).

**Comment by sjvrijn** [comment]
> I'll see if I can reproduce this on my Windows 10 machine.

I was unable to reproduce #2121 in Windows 10, while still reproducing it in Windows 11, so definitely seems to be a PySide/Windows issue.

> Updating PySide6 to 6.5 seems to prevent Toolbox from crashing ...

After upgrading PySide6 to 6.5.1.1, I was no longer able to reproduce #2121. Because the current requirements specify PySide<6.5.0, I had to upgrade it with the following command:
```bash
pip install --upgrade --force-reinstall PySide6
```

I'll make a PR to update the requirements.
