### ISSUE TITLE
Default message when committing a database? 

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2192]
Hello,
In SpineToolbox, when we make changes to a database and want to commit, we necessarily have to write a commit message.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/62605130/4feb809a-76d0-4fd8-9adf-f60c64fb712c)
It can be a bit heavy when doing numerous small non important modifications.
Have you considered having a default message? Either something a very basic sentence like "Updated DB", or something more elaborated, that would track what we did, e.g. "Added object XX to Unit. Updated parameter YY for object ZZ."

**Comment by jkiviluo** [comment]
The default message could be just 'Updated'. When this dialog pops up, the text box should be active with the text 'Updated' fully selected (so that it's easy to replace by just starting to type).

There is a question if we want to encourage bad behavior of not writing what you actually did... But I'm at least willing to give this a try.

**Comment by e-zaline** [comment]
Thank you @PiispaH  👍
