### ISSUE TITLE
Refresh doesn't bring back entities in the tree

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2300]
Open empty db, add class, add entity, commit, refresh. The entity doesn't show up after expanding the class.

Also, the refresh button shouldn't be really disabled ever because the user should be able to refresh at *any* moment. Refresh means reload data from the database, in case there are external changes.

**Comment by jkiviluo** [comment]
Disabling refresh/reload was implemented, since we're not handling the situation where there are conflicts with external changes. Maybe it's not the best solution, but we need to prevent situations where those conflicts can happen. 

Discussed at least here: https://github.com/spine-tools/Spine-Toolbox/issues/2252

**Comment by manuelma** [comment]
> Disabling refresh/reload was implemented, since we're not handling the situation where there are conflicts with external changes. Maybe it's not the best solution, but we need to prevent situations where those conflicts can happen.
> 
> Discussed at least here: #2252

Right, I missed that. Conflicts between external changes and non-committed changes in DB editor are now resolved in favour of the latter. You want me to restablish disabling the refresh button if there are dirty changes?

**Comment by jkiviluo** [comment]
I believe that's better, but I'm not able to think this through today (or in the next three days - meetings and traveling). So, do as you see best.
