### ISSUE TITLE
Undoing after rollback doesn't update Scenario tree

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2310]
1. Open empty database
2. Create new scenario (no need to add alternatives or anything)
3. Rollback. The scenario vanishes expectedly
4. Undo. The scenario should reappear but it does not

**Comment by PiispaH** [comment]
Is it supposed to be possible to undo the rollback? When rolling back a db the following warning comes up: "All your changes since the last commit will be reverted and removed from the undo/redo stack."

I got the scenario to show up again by pressing redo after step 4. When it showed up again DB editor thought that the DB didn't have any changes since the last commit and therefore the DB couldn't be committed with the newly added (still uncommitted) scenario. Is the issue here that the undo/redo stack isn't actually getting cleared after the rollback as it states?

**Comment by soininen** [comment]
> Is the issue here that the undo/redo stack isn't actually getting cleared after the rollback as it states?

Sound like the bug here is exactly that.

**Comment by manuelma** [comment]
I think you're right @PiispaH - rollback should clear the stack. We are calling setClean() on the stack whereas we should be calling clear() - or something like that.

**Comment by manuelma** [comment]
Note that commit is different. Commit should effectively set the stack clean rather than clearing it (it should be possible to undo and redo after commit)

**Comment by PiispaH** [comment]
@manuelma If changes are made and the db is committed and after that more changes are done after which the DB is rolled back, should the undo/redo stack from the moment of the commit still be available? In other words should the rollback only clear the undo/redo stack from the current state until the latest commit? That way it would be like the changes after the commit and the rollback never happened and it would still be possible to undo/redo changes before the commit. Other way is to just clear the whole stack and undo/redo isn't available after a rollback no matter what.

**Comment by manuelma** [comment]
@PiispaH I see what you mean, ideally rollback after commit should reset the index to that commit - although I don't know if that's possible with QUndoStack. I thought setIndex could work: just record the index at commit and then call setIndex with it after rollback - but setIndex calls undo/redo too, which we don't want.

So I believe it's ok to just clear the stack after rollback, even if there are 'commits in the stack' so to say. It's a bit of a corner case anyways? We can leave it like and see if a user complains (which I doubt).

**Comment by PiispaH** [comment]
Ok, will close this one for now then.
