### ISSUE TITLE
Restricting jinja2 < 3.0 creates dependabot security alert

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2517]
There is apparently a vulnerability in jinja2 < 3.1.3 which triggers a security alert when pushing to Spine-Database-API, spine-engine and Spine-Toolbox repositories because their `requirements.txt` files restrict jinja2 < 3.0 with a comment stating that the restriction comes from Dagster

We should just remove the restriction from Spine-Database-API because it does not depend on Dagster in any way.

I am not sure what to do with Spine-Engine, though. Perhaps we need to try to upgrade to latest Dagster?

**Comment by PekkaSavolainen** [comment]
The jinja2 requirement is in `spinedb_api/docs/requirements.txt` and it was added there so that the spinedb-api docs requirements would install the same version of Sphinx as `spinetoolbox/docs/requirements.txt`. If we don't do that, there is a dependency conflict (there is an older issue on this). I don't know how to deal with the security alert though. Do a lot of people actually install the docs requirements using the `spinedb-api/docs/requirements.txt`. Maybe we should remove it and point them to the spinetoolbox/docs/requirements.txt instead.

**Comment by soininen** [comment]
Thanks to ditching Dagster and updating our dependencies, all Dependabot security alerts in all four repositories are gone.
