### ISSUE TITLE
Julia tool compains it cannot find the julia executable

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2520]
Leave the path to the julia executable empty both in global toolbox settings and in the individual tool specification. Run the tool -> it complains you need to enter the path... But it should use the one from the user's PATH environment variable.

**Comment by PekkaSavolainen** [comment]
I think I fixed this already in #2460 but I'll take a second look. This happened to @DillonJ, right?

**Comment by manuelma** [comment]
And to myself. Thank you @PekkaSavolainen !

**Comment by PekkaSavolainen** [comment]
So, I'm guessing this red circle is empty for you. 

![issue_2520_missing_julia](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/843b30b0-abce-4125-9715-60b7678ddade)

If it's empty it means that spine toolbox did not find `julia.exe` file on Windows (or `julia` file on Linux) in any of the folders you have in your PATH (both global and user). One thing that could go wrong is that your Julia executable file name is something else than `julia.exe` or `julia`. Is this the case?

One way that I was able to reproduce this was to put my Julia bin folder into the USER PATH, then start Miniconda prompt in Admin mode. In this case, Spine Toolbox does not find julia.exe in my PATH because the Admin conda prompt only uses the system PATH.

**Comment by PekkaSavolainen** [comment]
@manuelma appreciate the thumbs up, but does it mean that you figured out the reason this happens on your system and you are good now?

How about @DillonJ, I presume you are on Windows, right? Can you please provide some additional info so I can get to the bottom of this:

1. Are you running toolbox in a Conda prompt, cmd.exe, powershell, or something else?
2. Are you running it as an administrator? 
3. Can you verify that running `julia` does in fact start the Julia REPL? 
4. What is the output of `where julia`? 
5. What is the output of `PATH`?

**Comment by PekkaSavolainen** [comment]
Could not reproduce.
