### ISSUE TITLE
App-execution reparse point cannot be selected as an executable for Basic Console

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2533]
Following the installation instructions at [Julia homepage](https://julialang.org/downloads/), the recommended way of installing Julia on Windows is from Microsoft Store. Pretty nice procedure, actually.

Anyway, when I try to change my Basic Console from here:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/bdca8bea-0beb-4638-a38e-c63937a84461)

I get this error when I select the freshly installed Julia.exe:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/17acf70a-580b-4f76-8889-3497fb531825)

This does not happen when I select Julia.exe that has been installed in a more conventional way.

Originally reported by @nelliputkonen

**Comment by PekkaSavolainen** [comment]
Looks like the `julia.exe` file in /Microsoft/WindowsApps/ folder is an *execution alias* and not the actual program executable. You can see that the .exe files in that folder are quite small (0 Bytes). They are protected somehow because you cannot even copy those files anywhere without an error dialog popping up.

A quick fix for this is to just ignore the error dialog by clicking ok, because Spine Toolbox did find julia.exe from your PATH (as evidenced by the placeholder text path) and this julia.exe (*execution alias*) **can be used** as the Julia executable for Basic Consoles out of the box (I tested). I.e. Close the settings box and execute a Julia Tool -> It should work.

If this does not work for some reason, you could try using julia.exe from the folder where Microsoft Store actually installed it to. On my system the Microsoft Store Julia is in:

![issue_2533_using_julia_from_micr_store](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/828349c0-0bad-46e9-8104-b8adea8cba7a)

Anyway, I'll try to find a way to deal with the *execution alias* julia.exe so that there's no error dialog if user's want to select that file manually for some reason.

**Comment by PekkaSavolainen** [comment]
Edited the title because the situation is not that dramatic. Microsoft Store Julia works fine and there's no need to browse to **%LocalAppData%\Microsoft\WindowsApps\julia.exe** because this is in every users PATH by default and it should appear into the executable line edit as placeholder text (gray text). If it doesn't, then that's a bug.

It looks like dealing with the warning dialog would require us to switch from the native Windows 'Open File' widget to Qt's own widget and I don't think it's worth the effort.
