### ISSUE TITLE
Titles in the settings pages don't show clearly because of the white background

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2586]

**Comment by PekkaSavolainen** [comment]
@jeenou Can you please provide a screenshot because I don't see this problem on my system?

**Comment by jeenou** [comment]
That description is a little bit misleading, sorry about that.  What I really meant here, is that the titles are not exactly according to the UX principles, since the font is quite small and also the white background kind of blends in to the background, so I didn't notice those titles at first. The black text of course shows better with the white background, but I think there could be a better solution here. 

![setting titles](https://github.com/spine-tools/Spine-Toolbox/assets/122606257/96fe4aba-1e57-458d-822e-370499bd43ad)

**Comment by PekkaSavolainen** [comment]
So, should I just bold the titles?

**Comment by jkiviluo** [comment]
I think you should increase font size a bit and make the text background something else than pure white, like light green.
Making something bold doesn't necessarily make it easier to read.

We should also get new color themes at some point, so better to probably have a background color and font size for 'choice box title font' that is easy to change in one place for all cases.

**Comment by PekkaSavolainen** [comment]
Increased the title font-size and edited the title background color. I think it now pops out a bit better without being distracting.

**Comment by PekkaSavolainen** [comment]
When we get a new color theme, UI design, and darkmode, we should look at these things as a whole. Closing...
