### ISSUE TITLE
0.7 entities always active are not active after migration to 0.8

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2611]
Entities that were always active on 0.7 like solve and commodity (had no is_active parameter) are active by default: false after migration to 0.8. 
The entities with is_active are correctly migrated.
Tested with 0.7 flextool database

**Comment by soininen** [comment]
This is expected behavior. You need to manually set active_by_default to True for the affected entity classes.

**Comment by DillonJ** [comment]
@jkiviluo are we still sure this is the desired expected behaviour? I think we are asking for trouble personally. It's the second issue on this already

**Comment by jkiviluo** [comment]
The migration should not break existing 0.7 models when going to 0.8. So, I think we're doing migration wrong. As 0.7 assumes that all objects that do not have is_active control, are sent to the tool, we should do the same by setting the active_by_default to True for all object classes that do not have is_active tool/feature set.

To @DillonJ comment: The current situation in FlexTool where some 0-d entities can end up in a model is actually dangerous, because those fray entities can cause the model to fail in unexpected ways. We have hopefully cornered all those cases manually in FlexTool code, but it would be better that the user has to choose to have them in the model with entity_alternative. This improves the awareness how the model works and what needs to be defined. It's better to give a friendly error message if something crucial is missing than to end up in a non-functional model.

Some of the fray entities can be harmless and therefore don't need entity_alternative control (e.g. commodity entity just gives a price to a commodity and it's not a big deal if the price is not used, just some memory loss), but some should be user controlled (e.g. model entities).

**Comment by soininen** [comment]
This was actually a misunderstanding on my part. The intention of spine-tools/Spine-Database-API#316 is to set active_by_default to 'true' in case no is_active is defined and I missed this.

**Comment by soininen** [comment]
Entities that were always active in 0.7 should now stay that way in 0.8 too.
