### ISSUE TITLE
Migration to 0.8 entity constraint is_active parameter not converted to active status

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2618]
When migrating to 0.8 the constraint entity is_active parameter is not creating entity alternative active: true like with nodes, connections and units

**Comment by soininen** [comment]
Can you attach the 0.7 database here or make it otherwise available?

**Comment by ArttuTupala** [comment]
[hydro_reservoir_with_pump.zip](https://github.com/spine-tools/Spine-Toolbox/files/14383486/hydro_reservoir_with_pump.zip)

**Comment by soininen** [comment]
Turns out this is not a bug. The database is missing tool_feature_method for the 'constraint' object class.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/02abcae9-2c99-487e-98bc-7bc4c3e88f64)

Without the tool_feature_method, database migration cannot identify the `is_active` parameter as the entity alternative.
