### ISSUE TITLE
Maximum value for penalty values to avoid loss of load?

### ISSUE THREAD

**Issue by amnanni** [spine-tools/Spine-Toolbox#2678]
I have a scenario where I want to test what investments does the model make if  I force it to have no loss of load. To model the no loss of load scenario, I set the penalty values for the demand node as high as possible. I found out that with value of 1e+14 the model was able to run but loss of load still existed (the model invested in PV, wind and battery but decided not to invest in thermal units and instead paid the penalty). Any values bigger thant 1e+14 (with nothing else than the penalty values changed) caused the following error:

Solving the presolved LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0     0.0000000000e+00 Pr: 8762(2.00547e+08) 0s
Model   status      : Not Set
HiGHS run time      :          2.85
2024-03-25 13:47:45 ERROR: Highs solver failed: 4294967295
Kernel died (×_×)

I understand that it's more feasible for the model to pay even the very high penalty than to build expensive thermal units, but is there anyway to workaround the too high penalty values to model the forced no loss of load scenario?

**Comment by DillonJ** [comment]
@amnanni  they would need to be very expensive thermal units for the model to choose to incur the penalty rather than invest. Have you tested your hypothesis by playing with the investment cost of the units concerned - even using a negative cost?

My suspicion is that something else is preventing your units from being invested in

**Comment by amnanni** [comment]
Thanks a lot for the comment, you're absolutely right, I was looking at the wrong thing! I started playing with the thermal unit investments and have to dig deeper since even the negative investment cost (when forced to invest with invest_min) give "The model is infeasible. Check the constraints."....

**Comment by amnanni** [comment]
I also just now noticed that I accidentally opened this as spine-toolbox issue and not as flextool, sorry!

**Comment by jkiviluo** [comment]
@amnanni I think you should have posted this in the FlexTool repository (can't transfer since it's different GitHub project). In short, you are having too wide range of variable range in the model and you're running into numeric infeasibilities. Maybe we can do something about that with more scaling - I will try to look into that once I have time. 

Meanwhile, use smaller penalty values and try to find out if something else is blocking the model from investing in the thermal plants (like a method not set correctly). As @DillonJ is saying, that penalty value seems so high that it should invest in thermal...
