### ISSUE TITLE
Change server default of active_by_default to true

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2744]
I wish I had remembered this before we merged 0.8. So with active_by_default = false by default, it simply looks as if your entities disappeared when you filter by a scenario. Many people who have tested it have fallen for it. It is very unintuitive in my opinion.

I suggest we add a new migration asap to change this setting.

It also makes everything more verbose, we need to change all scripts that add entity classes and all templates. It is a big breaking change.

**Comment by soininen** [comment]
@manuelma:

> What do you think?

I agree we must alter the 'server_default'.

By "new migration script" I hope you mean that we modify the *current* migration script so that it sets all `active_by_default`s to True if there is no `is_active` parameter definition, no matter how many dimensions there is. I do not think we can make an entirely *new* migration script for current 0.8 databases as we cannot know if users have willingly changed `active_by_default` already or accepted its current value. In any case, you can manually "fix" `active_by_default` in existing databases if needed, so it should not be a problem. At least new and migrated-from-0.7 databases will get the desired default `active_by_default`.

**Comment by manuelma** [comment]
Hi @soininen 

I mean new migration script - the alembic thing. If we modify the schema created by `create_new_spine_database()` we need to accompany that with a new migration script, otherwise there is risk of corruption. An older DB that goes through the migration path needs to have the same schema as the new DB created with `create_new_spine_database()`.

Apart from that, I think you're right we might want to modify the 'compatibitily transformation' function so if there is no is_active parameter definition, then active_by_default is set to True.

And now I am seeing that we also might need to fix `mapped_items.EntityClassItem.polish()`.

Just another clarification after re-reading your comment above. The new migration script just needs to change the server_default for active_by_default so newly created entity_classes get active_by_default = true if not specified. The script doesn't need to touch the value of active_by_default for existing classes in the DB; those are up to the user to fix manually as you correctly point out.

**Comment by soininen** [comment]
> Just another clarification after re-reading your comment above. The new migration script just needs to change the server_default for active_by_default so newly created entity_classes get active_by_default = true if not specified.

Ah, yes! I did not think the server_default here! Of course we need a migration script for that. Thanks for the heads-up!
