### ISSUE TITLE
Allow default alternatives in DB editor

### ISSUE THREAD

**Issue by nelliputkonen** [spine-tools/Spine-Toolbox#2790]
Create an option to choose a default alternative. This could be in Alternative right-click menu (when clicking a single alternative): "Make default" and the default could be indicated e.g. by having text "default" next to the alternative name (or simply being bolded or underlined or different color - however that might be too vague for the user to understand). By default, the "base" alternative (automatically in the database, right?) could be the default alternative.

Default alternatives are then used to give suggestions to Entity alternatives when adding entities (see issue: https://github.com/spine-tools/Spine-Toolbox/issues/2788), and later they can also be default for new parameters (no issue exists yet).

**Comment by PiispaH** [comment]
Would this default alternative be specific to the Data Store item, actual database or just the current session when the db editor is open?

**Comment by soininen** [comment]
I wonder if it would make more sense to to use the selected alternative on the Alternative dock as the one offered automatically instead of having to specify a default one explicitly. If there are more than one alternative selected, we could default to the current one (the one selected last, i.e. `currentIndex` in Qt parlance).

Parameter value table already works in a wonky manner if you have selected alternatives in the Alternatives dock and specify a non-selected alternative for the value: it just disappears from the table. This is, of course, correct behavior as the table is showing only selected alternatives, but is still surprising. No-one likes surprises. I feel defaulting to any other alternative than a selected one would just add to the confusion.

**Comment by PiispaH** [comment]
The way that @soininen proposed has been implemented in the above pull request. If no alternative is selected, the first alternative (normally Base) will be given as default in the *Add entities* -dialog.
