### ISSUE TITLE
Jupyter Consoles do not work in the bundled app

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2841]
Because the bundle is missing jupyter-client and qtconsole packages.

**Comment by PekkaSavolainen** [comment]
Done. Will be in the next development snapshot and upcoming releases.


The following is mostly for @soininen

There was a price to pay. The bundle grew by  ~100Mb and the number of files increased from about 8000 to 14000. This is all well and good but upload_artifact@v4 gave me a headache. I was hit by this issue https://github.com/actions/upload-artifact/issues/485 because of the increase in the number of files. I tried using Github's Powershell to create the .zip file (with Compress-Archive cmdlet) before running upload_artifact, so that it would only upload one file instead of 14000. This 'worked' but I was hit by another issue https://github.com/actions/upload-artifact/issues/39. The zip-file was inside another zip file, which I thought would be too confusing for first time users. I ended up using the soon-to-be-deprecated upload_artifact@v3, which does not have issue 485. Unfortunately, the Upload archive step is really slow with v3. I'll change it back to v4 if I get bored waiting and then we'll just have to live a with double zipped bundle until we find a solution.

**Comment by soininen** [comment]
@PekkaSavolainen Thanks a lot for working on this!

There is a problem with the bundle, though. You really cannot install anything that comes with .exe files such as Pip or Jupyter since the executable files in `_internal\Python\Scripts` will then have hard-coded paths to the system where the installation was done and do not work. Originally, I tried to have the embedded Python to come with Pip but for that reason I choose not to include it. I am not sure if this is actually an issue for the users since they probably will never try to run the .exe files but it is still a pity we ship a broken Python.

Also the increased bundle size and the issues that come with it worries me. Would it be a possibility to just disable Jupyter in Toolbox if the Python environment does not have it?
