### ISSUE TITLE
should the active value of a multi-dimensional entity classes in-/dependent on its composite entity classes?

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#3009]
For example, now we can set (under the same alternative) an entity of `unit__to_node` with "active=true" with its corresponding `unit` and/or `node` entity with "active=false".

**Comment by jkiviluo** [comment]
Even if you do that, the unit__to_node will not be part of the model. Both unit and node will need to be active for that to happen.

In principle, we should de-activate that option, but it is way too complicated due to alternatives - one needs to track in which scenarios those units and nodes are both active in order to know when unit__to_node can be set to active. We could possibly signal scenarios where this conflict happens, but not any time soon, since there are more important things to do.
